I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/y1_s2.rpy", line 4, in script
    b "Welcome to the Career and Internship Fair!"
Exception: Sayer 'b' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/y1_s2.rpy", line 4, in script
    b "Welcome to the Career and Internship Fair!"
  File "C:\Users\Ian\Downloads\renpy-7.4.11-sdk/renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Ian\Downloads\renpy-7.4.11-sdk/renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'b' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
CS 1.0
Wed Feb 23 02:14:38 2022
